name: del_colmado_rd
description: Aplicación móvil DelColmadoRD.
publish_to: "none"

# ↪️ Usa el SDK de Dart 3.x que trae Flutter 3.22 o superior
environment:
  sdk: ">=3.2.0 <4.0.0"

version: 1.0.0+1

################################################################################
# DEPENDENCIAS
################################################################################
dependencies:
  flutter:
    sdk: flutter

  # Iconos iOS estilo Cupertino
  cupertino_icons: ^1.0.2

  # --- Riverpod estable ---
  flutter_riverpod: ^2.6.1        # lógica y DI
  hooks_riverpod:  ^2.6.1
  riverpod_annotation: ^2.6.1     # anotaciones @riverpod

  # Mientras migras desde GetX → Riverpod mantén Get en el proyecto
  get: ^4.6.6

  # Otros paquetes UI / utilidades
  flutter_hooks: ^0.20.0
  dots_indicator: ^2.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

  # Geolocalización y mapas
  google_maps_flutter: ^2.5.4
  geocoding:           ^2.1.0
  geolocator:          ^9.0.2   # evita el parámetro altitudeAccuracy obligatorio de v10

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generación de código (Riverpod)
  riverpod_generator: ^2.6.5
  build_runner:       ^2.4.8

  # Lints recomendados por Flutter
  flutter_lints: ^3.0.1

  # Íconos de la app
  flutter_launcher_icons: ^0.13.0

################################################################################
# CONFIGURACIÓN DE flutter_launcher_icons
################################################################################
flutter_icons:
  android: true
  ios: true
  image_path: "assets/food_deliver_icon.png"
  adaptive_icon_foreground: "assets/play_store_512.png"
  adaptive_icon_background: "#FFFFFF"   # color de fondo para Android 12+

################################################################################
# FLUTTER
################################################################################
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
